// Catálogo de drywall y fibrocemento: lo que se usa en cielo raso de
// plancha, divisiones y acabados. El del cielo raso vinil va aparte, en
// materiales-vinil.js.
//
// PRECIOS REFERENCIALES: el administrador los edita desde Materiales.

import { SIMPLE } from './unidades.js';

export const MATERIALES_DRYWALL = [
  // --- Planchas ---
  {
    id: 'plancha-st-8',
    nombre: 'Plancha drywall estándar 8 mm (1.22 × 2.44 m)',
    dimensiones: { ancho: 1.22, largo: 2.44 },
    categoria: 'planchas',
    unidad: 'plancha',
    precioCompra: 26,
    precioVenta: 34,
    rendimiento: 2.9768,
    ...SIMPLE,
  },
  {
    id: 'plancha-st-127',
    nombre: 'Plancha drywall estándar 12.7 mm (1.22 × 2.44 m)',
    dimensiones: { ancho: 1.22, largo: 2.44 },
    categoria: 'planchas',
    unidad: 'plancha',
    precioCompra: 34,
    precioVenta: 44,
    rendimiento: 2.9768,
    ...SIMPLE,
  },
  {
    id: 'plancha-rh-127',
    nombre: 'Plancha drywall resistente a humedad 12.7 mm',
    dimensiones: { ancho: 1.22, largo: 2.44 },
    categoria: 'planchas',
    unidad: 'plancha',
    precioCompra: 46,
    precioVenta: 58,
    rendimiento: 2.9768,
    ...SIMPLE,
  },
  {
    id: 'plancha-st-95',
    nombre: 'Plancha drywall estándar 9.5 mm / 3/8" (1.22 × 2.44 m)',
    dimensiones: { ancho: 1.22, largo: 2.44 },
    categoria: 'planchas',
    unidad: 'plancha',
    precioCompra: 28,
    precioVenta: 37,
    rendimiento: 2.98,
    ...SIMPLE,
  },
  {
    id: 'plancha-fibrocemento-4',
    nombre: 'Plancha fibrocemento 4 mm (1.22 × 2.44 m)',
    dimensiones: { ancho: 1.22, largo: 2.44 },
    categoria: 'planchas',
    unidad: 'plancha',
    precioCompra: 38,
    precioVenta: 50,
    rendimiento: 2.98,
    ...SIMPLE,
  },
  {
    id: 'plancha-fibrocemento-8',
    nombre: 'Plancha fibrocemento 8 mm (1.22 × 2.44 m)',
    dimensiones: { ancho: 1.22, largo: 2.44 },
    categoria: 'planchas',
    unidad: 'plancha',
    precioCompra: 62,
    precioVenta: 80,
    rendimiento: 2.98,
    ...SIMPLE,
  },
  {
    id: 'plancha-fibrocemento-6',
    nombre: 'Plancha fibrocemento 6 mm (1.22 × 2.44 m)',
    dimensiones: { ancho: 1.22, largo: 2.44 },
    categoria: 'planchas',
    unidad: 'plancha',
    precioCompra: 48,
    precioVenta: 62,
    rendimiento: 2.9768,
    ...SIMPLE,
  },

  // --- Perfiles ---
  {
    id: 'riel-64',
    nombre: 'Riel 64 mm × 3.00 m',
    dimensiones: { largo: 3 },
    categoria: 'perfiles',
    unidad: 'barra',
    precioCompra: 11,
    precioVenta: 15,
    rendimiento: null,
    ...SIMPLE,
  },
  {
    id: 'parante-64',
    nombre: 'Parante 64 mm × 3.00 m',
    dimensiones: { largo: 3 },
    categoria: 'perfiles',
    unidad: 'barra',
    precioCompra: 12,
    precioVenta: 16,
    rendimiento: null,
    ...SIMPLE,
  },
  {
    id: 'riel-89',
    nombre: 'Riel 89 mm × 3.00 m',
    dimensiones: { largo: 3 },
    categoria: 'perfiles',
    unidad: 'barra',
    precioCompra: 14,
    precioVenta: 19,
    rendimiento: null,
    ...SIMPLE,
  },
  {
    id: 'parante-89',
    nombre: 'Parante 89 mm × 3.00 m',
    dimensiones: { largo: 3 },
    categoria: 'perfiles',
    unidad: 'barra',
    precioCompra: 15,
    precioVenta: 20,
    rendimiento: null,
    ...SIMPLE,
  },
  {
    id: 'omega',
    nombre: 'Perfil omega × 3.00 m',
    dimensiones: { largo: 3 },
    categoria: 'perfiles',
    unidad: 'barra',
    precioCompra: 9,
    precioVenta: 13,
    rendimiento: null,
    ...SIMPLE,
  },
  // --- Tornillería: se vende por ciento, se gasta de a uno ---
  {
    id: 'tornillo-drywall-1',
    nombre: 'Tornillo drywall 6 × 1" punta fina',
    categoria: 'tornilleria',
    unidad: 'ciento',
    unidadConsumo: 'tornillo',
    porVenta: 100,
    fraccionable: true,
    precioCompra: 4.5,
    precioVenta: 7,
    rendimiento: null,
  },
  {
    id: 'tornillo-drywall-158',
    nombre: 'Tornillo drywall 6 × 1 5/8" punta fina',
    categoria: 'tornilleria',
    unidad: 'ciento',
    unidadConsumo: 'tornillo',
    porVenta: 100,
    fraccionable: true,
    precioCompra: 6,
    precioVenta: 9,
    rendimiento: null,
  },
  {
    id: 'tornillo-fibrocemento',
    nombre: 'Tornillo fibrocemento 8 × 1 1/4" punta broca',
    categoria: 'tornilleria',
    unidad: 'ciento',
    unidadConsumo: 'tornillo',
    porVenta: 100,
    fraccionable: true,
    precioCompra: 9,
    precioVenta: 13,
    rendimiento: null,
  },
  {
    id: 'tornillo-framer',
    nombre: 'Tornillo framer 8 × 1/2"',
    categoria: 'tornilleria',
    unidad: 'ciento',
    unidadConsumo: 'tornillo',
    porVenta: 100,
    fraccionable: true,
    precioCompra: 5,
    precioVenta: 8,
    rendimiento: null,
  },

  // --- Fijación ---
  {
    // La caja trae 100 clavos y 100 fulminantes: van siempre de a par y no
    // se venden por separado, así que se cuenta el par.
    id: 'clavo-impacto',
    nombre: 'Combo clavo + fulminante (caja de 100 pares)',
    categoria: 'fijacion',
    unidad: 'caja',
    unidadConsumo: 'par',
    porVenta: 100,
    fraccionable: false,
    precioCompra: 12,
    precioVenta: 20,
    rendimiento: null,
  },
  {
    id: 'alambre-16',
    nombre: 'Alambre galvanizado N° 16',
    categoria: 'fijacion',
    unidad: 'kg',
    unidadConsumo: null,
    porVenta: 1,
    fraccionable: true,
    precioCompra: 8,
    precioVenta: 12,
    rendimiento: null,
  },
  {
    id: 'colgante',
    nombre: 'Colgante regulable',
    categoria: 'fijacion',
    unidad: 'unidad',
    precioCompra: 2.5,
    precioVenta: 4,
    rendimiento: null,
    ...SIMPLE,
  },

  // --- Acabados ---
  {
    id: 'masilla-28',
    nombre: 'Masilla lista, balde 28 kg',
    categoria: 'acabados',
    unidad: 'balde',
    unidadConsumo: 'kg',
    porVenta: 28,
    fraccionable: true,
    precioCompra: 68,
    precioVenta: 88,
    rendimiento: null,
  },
  {
    id: 'cinta-malla',
    nombre: 'Cinta malla de fibra 90 m',
    categoria: 'acabados',
    unidad: 'rollo',
    unidadConsumo: 'm',
    porVenta: 90,
    fraccionable: false,
    precioCompra: 9,
    precioVenta: 14,
    rendimiento: null,
  },
  {
    id: 'cinta-papel',
    nombre: 'Cinta de papel 75 m',
    categoria: 'acabados',
    unidad: 'rollo',
    unidadConsumo: 'm',
    porVenta: 75,
    fraccionable: false,
    precioCompra: 7,
    precioVenta: 11,
    rendimiento: null,
  },
  {
    // El fibrocemento no lleva cinta: las juntas se sellan y se masillan.
    id: 'sika-sellador',
    nombre: 'Sellador elastomérico, cartucho 300 ml',
    categoria: 'acabados',
    unidad: 'cartucho',
    precioCompra: 14,
    precioVenta: 20,
    rendimiento: null,
    ...SIMPLE,
  },
  {
    id: 'lija-120',
    nombre: 'Lija N° 120, pliego',
    categoria: 'acabados',
    unidad: 'pliego',
    precioCompra: 1.2,
    precioVenta: 2,
    rendimiento: null,
    ...SIMPLE,
  },

  // --- Aislamiento ---
  {
    id: 'lana-vidrio',
    nombre: 'Lana de vidrio, rollo 12 m²',
    categoria: 'aislamiento',
    unidad: 'rollo',
    unidadConsumo: 'm²',
    porVenta: 12,
    fraccionable: false,
    precioCompra: 95,
    precioVenta: 125,
    rendimiento: 12,
  },
];
